spring:
  h2:
    console:
      enabled: 'true'
  datasource:
    username: sa
    url: jdbc:h2:mem:db;MODE=MYSQL;
    password: ''
  jpa:
    generate-ddl: 'true'
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: create
    show-sql: 'true'
  thymeleaf:
    cache: 'false'
jwt:
  secret:
    key: 7ZWt7ZW0OTntmZTsnbTtjIXtlZzqta3snYTrhIjrqLjshLjqs4TroZzrgpjslYTqsIDsnpDtm4zrpa3tlZzqsJzrsJzsnpDrpbzrp4zrk6TslrTqsIDsnpA=


management:
  endpoints:
    web:
      exposure:
        include: health

